modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="onedeathforall"
version="1.1.0"
displayName="onedeathforall"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/DeltaXWizard/onedeathforall"
authors="DeltaXWizard"

[[dependencies.onedeathforall]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




